import { describe, expect, it } from 'vitest';
import { detectDrkallaUserProductType } from '../drkalla-product-type-detector.js';

describe('DrKalla product type detector', () => {
  it.each([
    ['Ich suche Haarfarben.', 'Haarfarbe/Farbcreme'],
    ['Habt ihr Salonwagen?', 'Salonmöbel/-ausstattung'],
    ['Habt ihr Sprühflaschen?', 'Salon-Verbrauchsmaterial'],
    ['Ich brauche Watteschnur.', 'Salon-Verbrauchsmaterial'],
    ['Habt ihr Spiegel?', 'Salon-Zubehör'],
    ['Ich suche einen Aufsteller.', 'Salon-Zubehör'],
    ['Ich suche einen Servicewagen.', 'Salon-Zubehör'],
    ['Habt ihr Kosmetikwagen?', 'Salon-Zubehör'],
    ['Ich brauche einen Haarsauger.', 'Friseur-Tool'],
    ['Habt ihr Clean All?', 'Friseur-Tool'],
    ['Ich suche Alligatorclips.', 'Styling'],
    ['Habt ihr Hair-Clips?', 'Styling'],
    ['Ich brauche Handtücher.', 'Salon-Verbrauchsmaterial'],
    ['Habt ihr Strähnenhauben?', 'Friseur-Tool'],
    ['Habt ihr Kosmetikbedarf?', 'Kosmetikbedarf'],
    ['Habt ihr Depilationszubehör?', 'Kosmetikbedarf'],
    ['Habt ihr Depilationswachs?', 'Kosmetikbedarf'],
    ['Ich brauche Hitzeschutz.', 'Haarpflege'],
    ['Ich brauche Haarpflege.', 'Haarpflege'],
    ['Habt ihr Ampullen?', 'Haarpflege'],
    ['Ich suche eine Haarkur.', 'Haarmaske'],
    ['Habt ihr eine klärende Spülung?', 'Conditioner/Spülung'],
    ['Ich suche Pflegespülung.', 'Conditioner/Spülung'],
    ['Ich suche Neutralshampoo.', 'Shampoo'],
    ['Habt ihr Haarfärbemittel?', 'Haarfarbe/Farbcreme'],
    ['Ich suche Nackenstreifen.', 'Salon-Verbrauchsmaterial'],
    ['Ich brauche Einweghandschuhe.', 'Salon-Verbrauchsmaterial'],
    ['Ich brauche ein professionelles Salonhandtuch.', 'Salon-Verbrauchsmaterial'],
    ['Habt ihr Salon-Verbrauchsmaterial?', 'Salon-Verbrauchsmaterial'],
    ['Habt ihr Haarschaum?', 'Styling'],
    ['Ich brauche Haarstyling.', 'Styling'],
    ['Ich brauche Bright-Wax.', 'Styling'],
    ['Habt ihr Stylingwax?', 'Styling'],
    ['Ich suche Gel-Spray.', 'Styling'],
    ['Habt ihr Volumen-Puder?', 'Styling'],
    ['Habt ihr Glanz-Spray?', 'Styling'],
    ['Habt ihr Laminier-Spray?', 'Styling'],
    ['Ich suche Vorbereitungsshampoo.', 'Shampoo'],
    ['Habt ihr Strähnchenfolie?', 'Friseur-Tool'],
    ['Ich brauche Blond-Booster.', 'Blondierung'],
    ['Habt ihr Desinfektionswagen?', 'Salonmöbel/-ausstattung'],
    ['Ich brauche eine UVC Lampe.', 'Friseur-Tool'],
    ['Habt ihr Accessories?', 'Salon-Zubehör'],
    ['Ich suche Zubehör.', 'Salon-Zubehör'],
    ['Habt ihr Salonbedarf?', 'Salon-Zubehör'],
    ['Ich brauche Barber-Bedarf.', 'Friseur-Tool'],
    ['Habt ihr einen Delrin Hair Comb?', 'Friseur-Tool'],
    ['Habt ihr einen Hair Dryer?', 'Friseur-Tool'],
    ['Ich suche einen konischen Heizstab.', 'Friseur-Tool'],
  ])('detects "%s" as %s', (text, expectedProductType) => {
    expect(detectDrkallaUserProductType(text)).toBe(expectedProductType);
  });
});
