export const SITE = 'https://phonbot.de';
export const TODAY = '2026-05-05';

export const CORE_INDUSTRY_PAGES = [
  {
    slug: 'friseur',
    name: 'Friseure',
    title: 'KI-Telefonassistent fuer Friseure',
    description: 'Termine, Oeffnungszeiten, Preisauskuenfte und Rueckrufwuensche fuer Salons.',
  },
  {
    slug: 'handwerker',
    name: 'Handwerker',
    title: 'KI-Telefonassistent fuer Handwerker',
    description: 'Auftragsannahme, Notdienst-Priorisierung und strukturierte Tickets.',
  },
  {
    slug: 'reinigung',
    name: 'Reinigungsfirmen',
    title: 'KI-Telefonassistent fuer Reinigungsfirmen',
    description: 'Angebotsanfragen, Objekt-Details und Besichtigungstermine.',
  },
  {
    slug: 'restaurant',
    name: 'Restaurants',
    title: 'KI-Telefonassistent fuer Restaurants',
    description: 'Reservierungen, Speisekarten-Fragen und Take-away-Anfragen.',
  },
  {
    slug: 'autowerkstatt',
    name: 'Autowerkstaetten',
    title: 'KI-Telefonassistent fuer Autowerkstaetten',
    description: 'Fahrzeugdaten, Werkstatttermine und Kostenvoranschlag-Tickets.',
  },
  {
    slug: 'selbststaendig',
    name: 'Selbststaendige',
    title: 'KI-Telefonassistent fuer Selbststaendige',
    description: 'Persoenlicher Telefonagent fuer Freelancer, Coaches und Solo-Betriebe.',
  },
];

export const SEO_NICHE_PAGES = [
  {
    slug: 'kosmetikstudio',
    name: 'Kosmetikstudios',
    title: 'KI-Telefonassistent fuer Kosmetikstudios & Beauty-Salons | Phonbot',
    description: 'Phonbot nimmt Anrufe fuer Kosmetikstudios an, bucht Behandlungen, beantwortet Preisfragen und erstellt Rueckruf-Tickets - 24/7 auf Deutsch.',
    eyebrow: 'KI-Telefonassistent fuer Kosmetikstudios',
    headline: 'Weniger Unterbrechungen in der Behandlung, mehr gebuchte Termine.',
    intro: 'Kosmetikstudios, Nagelstudios und Beauty-Salons verlieren Anfragen oft genau dann, wenn gerade eine Behandlung laeuft. Phonbot nimmt den Anruf sofort an, klaert Behandlung, Wunschzeit und Kontaktdaten und bucht passende Termine direkt in den Kalender.',
    audience: 'Kosmetikstudios, Nagelstudios, Beauty-Salons, Brow- und Lash-Studios',
    primaryKeyword: 'KI Telefonassistent Kosmetikstudio',
    secondaryKeywords: ['Telefonassistent Beauty Salon', 'automatische Terminbuchung Kosmetik', 'KI Anrufannahme Nagelstudio'],
    useCases: [
      ['Terminbuchung', 'Behandlungen, Dauer, Mitarbeiterin und Wunschzeit werden abgefragt, bevor der Termin bestaetigt wird.'],
      ['Preis- und Leistungsfragen', 'Phonbot erklaert Standardleistungen wie Gesichtsbehandlung, Manikuere, Wimpernlifting oder Paketpreise.'],
      ['Absagen und Umbuchungen', 'Kunden koennen telefonisch Termine verschieben; der Agent erstellt ein sauberes Rueckruf- oder Umbuchungs-Ticket.'],
      ['Warteliste', 'Wenn kein Slot frei ist, sammelt Phonbot Wunschzeiten und legt eine priorisierte Wartelisten-Anfrage an.'],
    ],
    callFlow: ['Anliegen erkennen', 'Behandlung und Dauer klaeren', 'Kalender pruefen', 'Termin bestaetigen', 'SMS oder Rueckruf-Ticket ausloesen'],
    pain: 'In einem Studio mit laufenden Behandlungen kann niemand mitten in der Arbeit ans Telefon gehen. Jeder verpasste Anruf ist ein potenzieller Termin bei einem anderen Studio.',
    faq: [
      ['Kann Phonbot verschiedene Behandlungen unterscheiden?', 'Ja. Im Agent Builder legst du Leistungen, Dauer, Preise und Mitarbeiterinnen an. Phonbot fragt gezielt nach.'],
      ['Kann der Agent bei Neukunden mehr Informationen sammeln?', 'Ja. Er fragt Kontaktdaten, Behandlungswunsch und relevante Hinweise ab und legt alles strukturiert ab.'],
      ['Kann ich fuer sensible Behandlungen Grenzen setzen?', 'Ja. Du kannst definieren, welche Fragen der Agent beantworten darf und wann ein Rueckruf noetig ist.'],
    ],
  },
  {
    slug: 'fahrschule',
    name: 'Fahrschulen',
    title: 'KI-Telefonassistent fuer Fahrschulen & Fahrstunden | Phonbot',
    description: 'Phonbot nimmt Anrufe fuer Fahrschulen an, beantwortet Kursfragen, sammelt Fahrschueler-Daten und koordiniert Rueckrufe oder Termine.',
    eyebrow: 'KI-Telefonassistent fuer Fahrschulen',
    headline: 'Anfragen zu Fuehrerschein, Theorie und Fahrstunden sofort beantworten.',
    intro: 'Fahrschulen bekommen viele wiederkehrende Telefonfragen: Preise, Theoriezeiten, Erste-Hilfe-Kurs, Anmeldung, Fahrstunden und Pruefungsvorbereitung. Phonbot nimmt diese Anrufe an und strukturiert die Anfrage, damit das Buero nicht dauernd aus dem Ablauf gerissen wird.',
    audience: 'Fahrschulen, Fahrlehrer, Ausbildungszentren',
    primaryKeyword: 'KI Telefonassistent Fahrschule',
    secondaryKeywords: ['Telefonbot Fahrschule', 'Fahrstunden automatisch koordinieren', 'KI Anrufannahme Fahrschule'],
    useCases: [
      ['Kursauskunft', 'Theoriekurse, Intensivkurse und Anmeldezeiten werden direkt erklaert.'],
      ['Neuanfragen qualifizieren', 'Phonbot sammelt Name, Klasse, Wohnort, Wunschstart und Rueckrufnummer.'],
      ['Fahrstunden-Wuensche', 'Der Agent nimmt Zeitfenster auf und erstellt ein Ticket fuer die passende Fahrlehrerin.'],
      ['Standardfragen', 'Kosten, Unterlagen, Ablauf und Erreichbarkeit werden konsistent beantwortet.'],
    ],
    callFlow: ['Fuehrerscheinklasse erkennen', 'Status abfragen', 'Wunschzeit aufnehmen', 'Daten pruefen', 'Rueckruf oder Termin ausloesen'],
    pain: 'Fahrlehrer sind unterwegs, das Buero ist nicht immer besetzt und Interessenten vergleichen schnell mehrere Fahrschulen. Eine sofortige Antwort gewinnt Vertrauen.',
    faq: [
      ['Kann Phonbot Preise und Kurszeiten nennen?', 'Ja. Du hinterlegst aktuelle Pakete, Theoriezeiten und Hinweise im Agent Builder.'],
      ['Kann der Agent Fahrstunden selbst eintragen?', 'Wenn ein Kalender verbunden ist, kann Phonbot passende Termine buchen oder als Ticket vorbereiten.'],
      ['Was passiert bei Pruefungsfragen?', 'Der Agent beantwortet einfache Ablauf-Fragen und leitet individuelle Pruefungsfaelle an das Team weiter.'],
    ],
  },
  {
    slug: 'immobilienmakler',
    name: 'Immobilienmakler',
    title: 'KI-Telefonassistent fuer Immobilienmakler & Besichtigungen | Phonbot',
    description: 'Phonbot qualifiziert Immobilienanfragen, sammelt Interessenten-Daten und koordiniert Besichtigungstermine fuer Makler - rund um die Uhr.',
    eyebrow: 'KI-Telefonassistent fuer Immobilienmakler',
    headline: 'Besichtigungsanfragen qualifizieren, bevor dein Telefon ueberlaeuft.',
    intro: 'Bei neuen Inseraten kommen viele Anrufe in kurzer Zeit. Phonbot fragt Objekt, Budget, Finanzierungsstatus und Wunschzeit ab, priorisiert passende Interessenten und erstellt strukturierte Tickets fuer Besichtigung oder Rueckruf.',
    audience: 'Immobilienmakler, Hausverwalter mit Vermietung, Projektvertrieb',
    primaryKeyword: 'KI Telefonassistent Immobilienmakler',
    secondaryKeywords: ['Besichtigungstermine automatisch koordinieren', 'Voice Bot Immobilien', 'Makler Anrufannahme KI'],
    useCases: [
      ['Besichtigungsanfragen', 'Objekt-ID, Personenanzahl, Budget und Zeitfenster werden sauber aufgenommen.'],
      ['Lead-Qualifizierung', 'Phonbot fragt Kauf- oder Mietinteresse, Finanzierung und Dringlichkeit ab.'],
      ['Rueckruf-Priorisierung', 'Sehr passende Interessenten landen mit hoher Prioritaet im Dashboard.'],
      ['Objekt-FAQ', 'Standardfragen zu Lage, Groesse, Stellplatz oder Unterlagen werden beantwortet.'],
    ],
    callFlow: ['Objekt erkennen', 'Interessentendaten sammeln', 'Qualifizierung stellen', 'Zeitfenster aufnehmen', 'Besichtigung oder Ticket vorbereiten'],
    pain: 'Makler verlieren Chancen, wenn nach einem Inserat zwanzig Anrufe gleichzeitig kommen. Phonbot laesst keinen Lead in der Mailbox verschwinden.',
    faq: [
      ['Kann Phonbot Objektinformationen nutzen?', 'Ja. Du hinterlegst Expose-Daten oder kurze Objektinfos, die der Agent fuer Telefonfragen nutzt.'],
      ['Kann der Agent Interessenten vorqualifizieren?', 'Ja. Du definierst Fragen zu Budget, Einzugstermin, Finanzierung oder Personenanzahl.'],
      ['Kann Phonbot mehrere Objekte unterscheiden?', 'Ja. Der Agent fragt nach Objektname, Adresse oder Inserat und ordnet den Anruf zu.'],
    ],
  },
  {
    slug: 'versicherungsmakler',
    name: 'Versicherungsmakler',
    title: 'KI-Telefonassistent fuer Versicherungsmakler & Beratungstermine | Phonbot',
    description: 'Phonbot nimmt Anrufe fuer Versicherungsmakler an, qualifiziert Anliegen und bucht Beratungstermine ohne fachliche Beratung zu ersetzen.',
    eyebrow: 'KI-Telefonassistent fuer Versicherungsmakler',
    headline: 'Schaden, Angebot oder Beratung? Phonbot sortiert den Anruf vor.',
    intro: 'Versicherungsmakler brauchen schnelle Reaktion, duerfen aber komplexe Beratung nicht automatisiert versprechen. Phonbot nimmt Anliegen auf, fragt nach Sparte und Dringlichkeit, erstellt Tickets und bucht Beratungstermine, ohne individuelle Versicherungsberatung zu ersetzen.',
    audience: 'Versicherungsmakler, Finanzdienstleister mit Terminberatung, Agenturen',
    primaryKeyword: 'KI Telefonassistent Versicherungsmakler',
    secondaryKeywords: ['Versicherung Anrufannahme KI', 'Beratungstermine automatisch buchen', 'Voice Bot Versicherung'],
    useCases: [
      ['Schadenaufnahme', 'Sparte, Datum, Kurzbeschreibung und Rueckrufnummer werden strukturiert aufgenommen.'],
      ['Beratungstermine', 'Neukunden koennen telefonisch einen Beratungsslot anfragen oder buchen.'],
      ['Dokumentenhinweise', 'Phonbot nennt allgemeine Unterlagen, die fuer den Rueckruf hilfreich sind.'],
      ['Priorisierung', 'Dringende Schadenfaelle werden hoeher priorisiert als allgemeine Tariffragen.'],
    ],
    callFlow: ['Anliegen klassifizieren', 'Sparte erkennen', 'Daten aufnehmen', 'Dringlichkeit setzen', 'Beratungstermin oder Ticket erstellen'],
    pain: 'Viele Anrufe sind wichtig, aber nicht jeder Anruf braucht sofort den Makler. Phonbot filtert sauber, damit Beratung konzentriert stattfinden kann.',
    faq: [
      ['Gibt Phonbot Versicherungsberatung?', 'Nein. Phonbot sammelt Informationen, beantwortet allgemeine Prozessfragen und bucht Termine. Individuelle Beratung bleibt beim Makler.'],
      ['Kann der Agent Schadenfaelle aufnehmen?', 'Ja, als strukturierte Erstaufnahme mit Rueckruf-Ticket und Prioritaet.'],
      ['Kann ich feste Compliance-Grenzen hinterlegen?', 'Ja. Du bestimmst, welche Aussagen erlaubt sind und welche Anliegen weitergeleitet werden.'],
    ],
  },
  {
    slug: 'fitnessstudio',
    name: 'Fitnessstudios',
    title: 'KI-Telefonassistent fuer Fitnessstudios & Probetrainings | Phonbot',
    description: 'Phonbot beantwortet Anrufe fuer Fitnessstudios, bucht Probetrainings, erklaert Tarife und erstellt Rueckruf-Tickets.',
    eyebrow: 'KI-Telefonassistent fuer Fitnessstudios',
    headline: 'Probetrainings buchen, waehrend dein Team auf der Flaeche ist.',
    intro: 'Fitnessstudios bekommen viele Anrufe zu Probetraining, Kursplan, Oeffnungszeiten, Preisen und Vertragsfragen. Phonbot beantwortet wiederkehrende Fragen und bucht Interessenten in freie Probetraining-Slots.',
    audience: 'Fitnessstudios, Personal-Training-Studios, EMS-Studios, Boutique-Gyms',
    primaryKeyword: 'KI Telefonassistent Fitnessstudio',
    secondaryKeywords: ['Probetraining automatisch buchen', 'Fitnessstudio Anrufannahme KI', 'Telefonbot Fitnessstudio'],
    useCases: [
      ['Probetraining buchen', 'Name, Ziel, Wunschzeit und Kontakt werden aufgenommen und im Kalender gebucht.'],
      ['Kursplan-Fragen', 'Phonbot beantwortet Fragen zu Kursen, Oeffnungszeiten und Standort.'],
      ['Tarif-Auskunft', 'Standardtarife und Startangebote werden konsistent erklaert.'],
      ['Rueckruf fuer Beratung', 'Komplexe Vertrags- oder Gesundheitsfragen werden an das Team weitergegeben.'],
    ],
    callFlow: ['Interessent erkennen', 'Ziel und Wunschzeit fragen', 'Kalender pruefen', 'Probetraining bestaetigen', 'Team informieren'],
    pain: 'Wenn Trainer im Kurs oder auf der Trainingsflaeche sind, bleiben Anrufe liegen. Gerade Probetrainings muessen schnell bestaetigt werden.',
    faq: [
      ['Kann Phonbot Probetrainings direkt buchen?', 'Ja, mit verbundenem Kalender bucht der Agent passende Slots.'],
      ['Kann der Agent Gesundheitsfragen beantworten?', 'Nur allgemeine Hinweise. Individuelle Trainings- oder Gesundheitsberatung wird weitergeleitet.'],
      ['Kann Phonbot Kurse und Tarife aktuell halten?', 'Ja. Du pflegst Kurszeiten und Tarife im Agent Builder oder in der Wissensbasis.'],
    ],
  },
  {
    slug: 'energieberater',
    name: 'Energieberater',
    title: 'KI-Telefonassistent fuer Energieberater & Sanierungsanfragen | Phonbot',
    description: 'Phonbot nimmt Sanierungs- und Foerderanfragen fuer Energieberater auf, qualifiziert Leads und plant Rueckrufe oder Ersttermine.',
    eyebrow: 'KI-Telefonassistent fuer Energieberater',
    headline: 'Sanierungsanfragen sortieren, bevor der Beratungskalender voll ist.',
    intro: 'Energieberater bekommen viele Anfragen zu Foerderung, Sanierungsfahrplan, Heizung, Dach und Energieausweis. Phonbot nimmt die Eckdaten auf und priorisiert passende Erstgespraeche, ohne fachliche Foerderberatung zu ersetzen.',
    audience: 'Energieberater, Sanierungsberater, Solar- und Effizienz-Dienstleister',
    primaryKeyword: 'KI Telefonassistent Energieberater',
    secondaryKeywords: ['Sanierungsanfragen automatisch aufnehmen', 'Foerderanfrage Telefon KI', 'Voice Bot Energieberatung'],
    useCases: [
      ['Erstanfrage aufnehmen', 'Objektart, Baujahr, Vorhaben, Ort und Zeitdruck werden strukturiert abgefragt.'],
      ['Rueckruf vorbereiten', 'Alle relevanten Eckdaten landen im Ticket, damit der Rueckruf schneller ist.'],
      ['Terminplanung', 'Geeignete Erstgespraeche koennen direkt im Kalender geplant werden.'],
      ['FAQ beantworten', 'Allgemeine Fragen zu Ablauf, Unterlagen und naechsten Schritten werden erklaert.'],
    ],
    callFlow: ['Vorhaben erkennen', 'Objektdaten aufnehmen', 'Dringlichkeit klaeren', 'Unterlagen nennen', 'Erstgespraech oder Ticket erstellen'],
    pain: 'Foerder- und Sanierungsanfragen sind oft zeitkritisch. Eine schnelle, strukturierte Erstaufnahme trennt gute Leads von unklaren Anfragen.',
    faq: [
      ['Gibt Phonbot Foerderberatung?', 'Nein. Phonbot sammelt Daten und erklaert allgemeine Ablaufe; fachliche Beratung bleibt beim Experten.'],
      ['Kann der Agent Objektdaten erfassen?', 'Ja. Baujahr, Objektart, Standort, geplante Massnahme und Rueckrufnummer koennen abgefragt werden.'],
      ['Kann Phonbot dringende Faelle markieren?', 'Ja. Du definierst Kriterien wie Fristen, Foerderfenster oder akute Heizungsthemen.'],
    ],
  },
  {
    slug: 'hausverwaltung',
    name: 'Hausverwaltungen',
    title: 'KI-Telefonassistent fuer Hausverwaltungen & Mieteranfragen | Phonbot',
    description: 'Phonbot nimmt Mieteranrufe fuer Hausverwaltungen an, erstellt Stoerungs-Tickets und priorisiert dringende Faelle.',
    eyebrow: 'KI-Telefonassistent fuer Hausverwaltungen',
    headline: 'Mieteranfragen aufnehmen, priorisieren und sauber dokumentieren.',
    intro: 'Hausverwaltungen erhalten viele Telefonate zu Schaeden, Terminen, Nebenkosten, Schluesseln oder Handwerkerbesuchen. Phonbot fragt Objekt, Wohnung, Problem und Erreichbarkeit ab und erstellt ein Ticket mit Prioritaet.',
    audience: 'Hausverwaltungen, WEG-Verwaltungen, Property Manager',
    primaryKeyword: 'KI Telefonassistent Hausverwaltung',
    secondaryKeywords: ['Mieteranfragen automatisch aufnehmen', 'Stoerungsticket Telefon KI', 'Voice Bot Hausverwaltung'],
    useCases: [
      ['Stoerungsmeldung', 'Adresse, Einheit, Schadensbild, Dringlichkeit und Kontakt werden aufgenommen.'],
      ['Terminabstimmung', 'Phonbot sammelt Zeitfenster fuer Handwerker- oder Besichtigungstermine.'],
      ['FAQ fuer Mieter', 'Standardfragen zu Erreichbarkeit, Unterlagen oder Prozessen werden beantwortet.'],
      ['Notfall-Priorisierung', 'Wasser, Strom oder Heizung koennen als dringende Tickets markiert werden.'],
    ],
    callFlow: ['Objekt identifizieren', 'Anliegen klassifizieren', 'Dringlichkeit setzen', 'Kontakt und Zugang klaeren', 'Ticket erstellen'],
    pain: 'Wenn alle Mieter gleichzeitig anrufen, entstehen unvollstaendige Notizen. Phonbot bringt Struktur in jeden Anruf.',
    faq: [
      ['Kann Phonbot Notfaelle erkennen?', 'Ja. Schlagworte und Regeln fuer Wasser, Strom, Heizung oder Zugang koennen hohe Prioritaet ausloesen.'],
      ['Kann der Agent verschiedene Objekte unterscheiden?', 'Ja. Objektlisten und Adressen lassen sich hinterlegen.'],
      ['Kann Phonbot Tickets an Mitarbeiter verteilen?', 'Ja. Ueber Routing-Regeln oder Benachrichtigungen koennen Tickets an die passenden Personen gehen.'],
    ],
  },
  {
    slug: 'ferienwohnung',
    name: 'Ferienwohnungen',
    title: 'KI-Telefonassistent fuer Ferienwohnungen & Gastgeber | Phonbot',
    description: 'Phonbot beantwortet Gaesteanrufe, sammelt Buchungsanfragen und erstellt Tickets fuer Ferienwohnungen, Apartments und kleine Hotels.',
    eyebrow: 'KI-Telefonassistent fuer Ferienwohnungen',
    headline: 'Gaesteanfragen beantworten, auch wenn du gerade nicht erreichbar bist.',
    intro: 'Gastgeber bekommen Anrufe zu Verfuegbarkeit, Check-in, Parkplatz, Haustieren, Rechnung und kurzfristigen Buchungswuenschen. Phonbot beantwortet Standardfragen und sammelt Buchungsdaten fuer den Rueckruf.',
    audience: 'Ferienwohnungen, Apartments, Pensionen, kleine Hotels',
    primaryKeyword: 'KI Telefonassistent Ferienwohnung',
    secondaryKeywords: ['Gaesteanfragen automatisch beantworten', 'Telefonbot Gastgeber', 'KI Anrufannahme Ferienwohnung'],
    useCases: [
      ['Buchungsanfrage', 'Zeitraum, Personenanzahl, Haustiere und Kontaktdaten werden aufgenommen.'],
      ['Check-in-FAQ', 'Anreise, Schluessel, Parkplatz und WLAN koennen konsistent beantwortet werden.'],
      ['Dringende Gaesteanliegen', 'Probleme vor Ort werden als priorisierte Tickets angelegt.'],
      ['Mehrsprachige Anrufe', 'Phonbot kann gaengige Sprachen fuer touristische Anfragen nutzen.'],
    ],
    callFlow: ['Anfrageart erkennen', 'Zeitraum und Personen aufnehmen', 'FAQ beantworten', 'Dringlichkeit setzen', 'Ticket oder Rueckruf erstellen'],
    pain: 'Gerade kleine Gastgeber koennen nicht rund um die Uhr ans Telefon. Trotzdem erwarten Gaeste schnelle Antworten vor und waehrend des Aufenthalts.',
    faq: [
      ['Kann Phonbot Verfuegbarkeit pruefen?', 'Mit angebundenem Kalender kann der Agent freie Zeitraeume pruefen oder die Anfrage als Ticket vorbereiten.'],
      ['Kann der Agent Check-in-Fragen beantworten?', 'Ja. Du hinterlegst Anreiseinfos, Parkplatz, WLAN, Hausregeln und Kontaktwege.'],
      ['Kann Phonbot mehrere Sprachen sprechen?', 'Ja. Phonbot unterstuetzt ueber 30 Sprachen, fuer Deutsch und viele weitere Sprachen mit natuerlichen Stimmen.'],
    ],
  },
];

export const SUPPORT_PAGES = [
  {
    slug: 'branchen',
    name: 'Branchenuebersicht',
    title: 'KI-Telefonassistent nach Branche | Phonbot',
    description: 'Alle Phonbot-Branchen: Friseure, Handwerker, Reinigung, Restaurants, Kosmetikstudios, Fahrschulen, Immobilienmakler und weitere Nischen.',
  },
  {
    slug: 'kontakt',
    name: 'Kontakt',
    title: 'Kontakt zu Phonbot | KI-Telefonassistent testen',
    description: 'Kontakt zu Phonbot: Demo anfragen, KI-Telefonassistent testen oder Fragen zu Preisen, DSGVO und Einrichtung klaeren.',
  },
];

export const ALL_INDUSTRY_PAGES = [...CORE_INDUSTRY_PAGES, ...SEO_NICHE_PAGES];
export const ALL_SEO_PAGE_SLUGS = [
  ...SUPPORT_PAGES.map((page) => page.slug),
  ...CORE_INDUSTRY_PAGES.map((page) => page.slug),
  ...SEO_NICHE_PAGES.map((page) => page.slug),
];
